#!/bin/sh

# ScratchPad Session
function work.scratch() {
	bbedit "/Users/Neo/Documents/Scratch"
}

# Productivity Sessions
function work.ppap() {
    open "http://presentationpatterns.com"
	open "http://www.amazon.com/Presentation-Patterns-Techniques-Crafting-Presentations/dp/0321820800/ref=sr_1_1?ie=UTF8&qid=1347145745&sr=8-1&keywords=presentation+patterns"
	open "https://github.com/presentationPatterns"
	open "https://github.com/PresentationPatterns/presentationpatterns.github.com"

	open "~/Dropbox/AI-Clients/Presentation-Patterns-Book"
	open "~/Dropbox/PPAP"
    iterm "~/Dropbox/AI-Clients/Presentation-Patterns-Book" "PPAP-Book" "black"
	iterm "~/Dropbox/PPAP" "PPAP-Dropbox" "black"
	iterm "~/Dropbox/AI-Clients/Presentation-Patterns-Book/presentationpatterns.github.com" "PPAP-Site" "black"
}

function work.teachgit() {
    open "https://github.com/githubtrainer/hellogitworld" -a "Firefox"
	open "https://github.com/githubstudent" -a "Google Chrome"
	
	open "https://github.com/github/teach.github.com"
	open "https://github.com/training/free"
	open "https://github.com/matthewmccullough/dotfiles"

	open "~/Documents/Temp/Scratch"
    iterm "~/Documents/Temp/Scratch" "Scratch" "black"
}


function work.gittraining() {
    open "https://github.com/githubtraining"
    open "https://github.com/github/training/issues"
    open "https://github.com/github/teach.github.com"

    open "~/Documents/Code/GitHub"
    open "~/Documents/Code/GitHub/training.github.com_git"
    open "~/Documents/Code/GitHub/GUTS_git"
    open "~/Documents/Code/GitHub/teach.github.com"
}


function fixbluetooth() {
  sudo killall coreaudiod
  sudo killall blued
  sudo renice -5 (pid bluetoothaudio)
  sudo renice -5 (pid iTunes)
  defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Max (editable)" 80
  defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" 80
  defaults write com.apple.BluetoothAudioAgent "Apple Initial Bitpool (editable)" 80
  defaults write com.apple.BluetoothAudioAgent "Apple Initial Bitpool Min (editable)" 80
  defaults write com.apple.BluetoothAudioAgent "Negotiated Bitpool" 80
  defaults write com.apple.BluetoothAudioAgent "Negotiated Bitpool Max" 80
  defaults write com.apple.BluetoothAudioAgent "Negotiated Bitpool Min" 80
  sudo renice -5 (pid coreaudiod)
  sudo renice -5 (pid blued)
}

function setup.python2() {
 export PATH=/usr/local/share/python:$PATH
 export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
 export WORKON_HOME=/Users/Neo/Developer/Environment/pyvirtualenvs/python2
 export PIP_VIRTUALENV_BASE=$WORKON_HOME
 export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2
 export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
 export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
 source /usr/local/bin/virtualenvwrapper.sh
}

function setup.python3() {
 export PATH=/usr/local/share/python:$PATH
 export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
 export WORKON_HOME=/Users/Neo/Developer/Environment/pyvirtualenvs/python3
 export PIP_VIRTUALENV_BASE=$WORKON_HOME
 export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
 export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
 export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
 source /usr/local/bin/virtualenvwrapper.sh
}
